apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: desafio11
  labels:
    app: desafio11

spec:
  replicas: 4
  selector:
    matchLabels:
      app: desafio11
  template:
    metadata:
      labels:
        app: desafio11
    spec:
      containers:
      - name: desafio11
        image: fabrof/desafio9:latest
        ports:
          - containerPort: 8081
